### ISSUE TITLE
Chrome商店版本无法正常使用

### ISSUE THREAD

**Issue by ufan0** [0jinxing/just-proxy#1]
如题，安装后无法正常代理；
查看本地日志发现并未成功代理；
然后下载此处的crx解压安装，能够正常工作。

另：非常棒的工具，感谢！

**Comment by 0jinxing** [comment]
![image](https://user-images.githubusercontent.com/32119282/72865049-57808400-3d11-11ea-8169-400446c3fffb.png)
应该是 Chrome 商店的版本，代理地址没有默认值。

**Comment by 0jinxing** [comment]
chrome 商店里面的，多了几个功能
1. 资源加载失败状态检测（就最下面的 tag，点击就可以加入代理）
2. 自定义代理（第二个输入框）
3. 可删除代理规则（选中规则---点击前面的序号，按下 delete 键 ）

**Comment by ufan0** [comment]
谢谢您，我已经成功使用上商店版本。

之前使用错误是在`更新代理服务器`一栏加上了socks或者http前缀导致。

删去前缀后，成功使用了http协议的代理（socks协议的会在v2ray报错`rejected  v2ray.com/core/proxy/socks: unknown Socks version: 67`）。
